### ISSUE TITLE
generated proper install-registry.sh / router.sh

### ISSUE THREAD

**Issue by fridim** [redhat-cip/rcip-openshift-ansible#11]
For now those scripts were only examples.  Use the playbook to set up them properly.

for example : install-registry.sh should not come with the option --mount-host  if not needed
- review all the options. 

The idea is when post.yml ansible is done, scripts can be safely run.

**Comment by talset** [comment]
We need to 
- clean the deprecated option (like inside the create certificat)
- remove mount-host
- add exemple to attach a pvc (volume) to the registry
