### ISSUE TITLE
improve "openshift-router-proc" check

### ISSUE THREAD

**Issue by fridim** [redhat-cip/rcip-openshift-ansible#14]
Currently the check openshift-router-proc is for masters:

```
//Proc
"openshift-router-proc": {
  "command": "/usr/local/bin/check-process.rb -p 'openshift-router' -C 1",
  "subscribers": [
    "openshift-master"
  ],
  "handlers": ["mailer", "flowdock"],
  "occurrences": 3,
  "refresh": 86400,
  "interval": 60
},
```

This may be an issue when:
- the number of replicats for routers is less than the number of masters (you will receive false-positive CRITICAL)
- infra node for routers are not necessarly masters

**Comment by xlr-8** [comment]
This commit start the work to avoid this situation:
https://github.com/redhat-cip/rcip-openshift-scripts/commit/474d00c49f14a3d5a1a02b6a19ec6f293324bedf

**Comment by talset** [comment]
ok for me
