### ISSUE TITLE
fix exception handling in rcip_openshift.fact

### ISSUE THREAD

**Issue by fridim** [redhat-cip/rcip-openshift-ansible#15]
There is too many level of exception handlers : too many try/except at different scopes

This creates a bug in certain conditions: double output like

```
bash-4.2# /etc/ansible/facts.d/rcip_openshift.fact
{"default": {"services": {"error": "tokenfile-inaccessible"}}}
{"default": {"services": {"error": "could not find masterURL"}}}
```

**Comment by talset** [comment]
To reproduce master controllers and api need to be stopped
