### ISSUE TITLE
sensu: flowdock notifications should be optional

### ISSUE THREAD

**Issue by fridim** [redhat-cip/rcip-openshift-ansible#16]
if <code>sensu_flowdock_auth_token</code> is not defined, ansible playbook stop with the following error:

TASK: [sensu | sensu handler config] *****************************************\* 
fatal: [monitoring.fridim.lab] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'sensu_flowdock_auth_token' is undefined", 'failed': True}
fatal: [monitoring.fridim.lab] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'sensu_flowdock_auth_token' is undefined", 'failed': True}]}

FATAL: all hosts have already failed -- aborting

**Comment by talset** [comment]
Fixed here : https://github.com/redhat-cip/rcip-openshift-ansible/commit/671955ea855917702c65ca44942f7606beb3e5e1
