### ISSUE TITLE
NTP server and atomic config

### ISSUE THREAD

**Issue by talset** [redhat-cip/rcip-openshift-ansible#29]
In some setup we can't have access to public  NTP server. We should have the possibility to setup a ntp server on at least the monitoring node.

We also have to review the configuration of ntp on atomic host
- Setup NTP server
- Configure NTP on atomic host

**Comment by gaelL** [comment]
For the atomic client part, they seems to use chrony.

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Using_chrony.html
