### ISSUE TITLE
sensu, uchiwa, check disk space

### ISSUE THREAD

**Issue by nevenr** [redhat-cip/rcip-openshift-ansible#52]
For atomic:
1. check does existing check for host root disk works correctly 
2. provide a way to check etcd disk space 
2.1 maybe as more generic solution find a way to check all mounted volumes

**Comment by talset** [comment]
+1 we can use a generic check to monitor all the mounted FS, not only one by one

**Comment by nevenr** [comment]
Hi,

when we talk about disk / volume space (total,used,free) we should make clear distinction between ones attached directly to host and ones attached to pod (container).

I think this should be two checks/plugins.
1. Host
   Dynamically detect all attached volumes attached to host (mount / df / fstab) and perform check against each one of them.
2. Pods
   For all pods on host or predefined list dynamically detect attached / claimed volumes and perform check against each one of them.

With this we could cover all disk/volume usage monitoring.

Cheers,
N.

**Comment by talset** [comment]
1. https://github.com/redhat-cip/rcip-openshift-ansible/commit/d77817514440cf218da69e24120451c3c385faa0
2. https://github.com/redhat-cip/rcip-openshift-ansible/commit/00659a1ef4d9eb4beb46b81e39570b17a7d3dd9f
