### ISSUE TITLE
docker-storage-setup fails on OSE 3.2 

### ISSUE THREAD

**Issue by akram** [redhat-cip/rcip-openshift-ansible#60]
Hi,
While trying to run pre.yaml on a 6 machines cluster: 3 nodes (medium), 3 masters (small 2GB RAM, 20GB disk), I got the following issue on first run: 

```
stderr: /bin/docker-storage-setup: line 394: ​* 2 - 2048 : syntax error: operand expected (error token is "*​ 2 - 2048 ")
```

it looks like the command cat /proc/partititions may have return a bad value.
Here is mine after the failure

```

 252        0   20971520 vda
 252        1     307200 vda1
 252        2   20663216 vda2
 253        0    3072000 dm-0
 253        1      24576 dm-1
 253        2    7024640 dm-2
 253        3    7024640 dm-3
```

**Comment by fridim** [comment]
Hi @akram,

did you set <code>customer_docker_storage_dev</code> ?

pre will set DEVS and VG,  in <code>/etc/sysconfig/docker-storage-setup</code> before running docker-storage-setup

If device was properly set, and there is something wrong with the script, you might want to report to atomicproject instead. I think it's there: https://github.com/projectatomic/docker-storage-setup
